name: 'PR Codeowner Autolabel Action'
description: 'Add labels to GitHub PRs based on the contents of CODEOWNERS file'
author: '@mdzhang'

inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  file-path:
    description: 'Relative path to CODEOWNERS in repo'
    required: false
    default: CODEOWNERS
  labels-to-owners:
    description:
      'Keys are labels to add, values are potential owners in CODEOWNERS.  These are treated as overrides if enable-default-labels is true.  This input is required but it can be empty.'
    required: true
  enable-default-labels:
    description: 'If no labels-to-owners are provided, default labels will be added based on the team name.  The organization will be removed.'
    required: false
    type: boolean
    default: false

runs:
  using: node20
  main: dist/index.js
